let suggestions = [
  "Abacavir 300 mg tablet",
  "Acetazolamide 250 mg Tablet",
  "Acetylcysteine 100 mg Oral Powder Sachet",
  "Acetylcysteine 100 mg/mL, 3 mL Respiratory Solution Ampule",
  "Acetylcysteine 200 mg Oral Powder Sachet",
  "Acetylcysteine 200 mg/mL, 25 mL Solution for Injection Bottle",
  "Acetylcysteine 600mg Effervescent Tablet",
  "Aciclovir 200 mg Tablet",
  "Aciclovir 25 mg/mL, 10 mL Solution for Injection Vial",
  "Aciclovir 400 mg Tablet",
  "Aciclovir 800 mg Tablet",
  "Adenosine 3 mg/mL, 2 mL Solution for Injection Vial",
  "Albumin, Human 20%, 50 mL Solution for Injection Bottle",
  "Albumin, Human 25%, 50 mL Solution for Injection Bottle",
  "Alendronate 70 mg Tablet",
  "All-in-one Admixtures 1000 Kcal",
  "All-in-one Admixtures 1400 Kcal",
  "All-in-one Admixtures 1900 Kcal",
  "Allopurinol 100 mg Tablet",
  "Allopurinol 300 mg Tablet",
  "Alprazolam 250 mcg Tablet",
  "Alprazolam 500 mcg Tablet",
  "Aluminum Hydroxide . Magnesium Hydroxide 225 mg 200 mg/5 mL, 60 mL Oral Suspension Bottle",
  "Aluminum Hydroxide + Magnesium Hydroxide 200 mg + 100 mg Tablet",
  "Aluminum Hydroxide Magnesium Hydroxide 225 mg 200 mg/5 mL, 120 mL Oral Suspension Bottle",
  "Amikacin 125 mg/mL, 2 mL Solution for Injection Ampule",
  "Amikacin 125 mg/mL, 2 mL Solution for Injection Vial",
  "Amikacin 250 mg/mL, 2 mL Solution for Injection Ampule",
  "Amikacin 250 mg/mL, 2 mL Solution for Injection Vial",
  "Amikacin 50 mg/mL, 2 mL Solution for Injection Vial",
  "Amino Acid + Electrolytes + Glucose + Vitamin B1, 1000 mL Solution for Injection",
  "Amino Acid Electrolytes Glucose . Vitamin B1, 500 mL Solution for Injection",
  "Amino Acid Glucose (Sorbitol), 500 mL Solution for Injection Bottle",
  "Amino Acids, Crystalline Standard 6%, 100 mL Solution for Injection Bottle",
  "Amino Acids, Crystalline Standard 7%, 500 mL Solution for Injection Bottle",
  "Amino Acids, Crystalline Standard 8%, 500 mL Solution for Injection Bottle",
  "Aminophylline (Theophylline Ethylenediamine) 25 mg/mL. 10 mL Solution for Injection Ampule",
  "Amiodarone 200 mg Tablet",
  "Amiodarone 50 mg/mL, 3 mL Solution for Injection Ampule",
  "Amlodipine 10 mg Tablet",
  "Amlodipine 5 mg Tablet",
  "Amoxicillin 100 mg/mL, 15 mL Oral Drops",
  "Amoxicillin 250 mg Capsule",
  "Amoxicillin 250 mg/s mL, 60 mL Oral Suspension",
  "Amoxicillin 500 mg Capsule",
  "Amphotericin B (Lipid Complex) 5 mg/mL, 10 mL Suspension for Injection Vial",
  "Amphotericin B (Non-Lipid Complex) 50 mg Powder for Injection Vial",
  "Ampicillin + Sulbactam 1 g 500 mg Powder for Injection Vial",
  "Ampicillin + Sulbactam 500 mg + 250 mg Powder for Injection Vial",
  "Ampicillin 1 g Powder for Injection Vial",
  "Ampicillin 250 mg Powder for Injection Vial",
  "Ampicillin 500 mg Powder for Injection Vial",
  "Anastrazole 1 mg Film Coated Tablet",
  "Aripiprazole 10 mg Orodispersible Tablet",
  "Aripiprazole 10 mg Tablet",
  "Ascorbic Acid (Vitamin C) 100 mg/5 mL, 120 mL Syrup Bottle",
  "Ascorbic Acid (Vitamin C) 100 mg/mL, 15 mL Oral Drops Bottle",
  "Ascorbic Acid (Vitamin C) 100 mg/mL, 30 mL Oral Drops Bottle",
  "Ascorbic Acid (Vitamin C) 100 mg/s mL, 60 mL Syrup Bottle",
  "Ascorbic Acid (Vitamin C) 250 mg/mL, 2 mL Solution for Injection Ampule",
  "Ascorbic Acid (Vitamin C) 500 mg Tablet",
  "Asparaginase 10,000 IU Powder for Injection Vial",
  "Aspirin 80 mg Tablet",
  "Atenolol 50 mg Tablet",
  "Atorvastatin 10 mg Tablet",
  "Atorvastatin 20 mg Tablet",
  "Atorvastatin 40 mg Tablet",
  "Atorvastatin 80 mg Tablet",
  "Atracurium 10 mg/mL, 2.5 mL Solution for Injection Ampule",
  "Atropine 1 mg/mL, 1 mL Solution for Injection Ampule",
  "Azathioprine 50 mg tablet",
  "Azithromycin 200 mg/5 mL, 15 mL Oral Suspension Bottle",
  "Azithromycin 200 mg/5 mL, 60 mL Oral Suspension Bottle",
  "Azithromycin 250 mg Tablet",
  "Azithromycin 500 mg Powder for Injection Vial",
  "Azithromycin 500 mg Tablet",
  "Aztreonam 1 g Powder for Injection",
  "Baclofen 10 mg Tablet",
  "Balanced Multiple Maintenance Solution + Dextrose 5%, 1L Solution for Injection Bottle",
  "Balanced Multiple Maintenance Solution + Dextrose 5%, 500 mL Solution for Injection Bottle",
  "Balanced Multiple Replacement Solution, 1L Solution for Injection Bottle (with pH 7.4)",
  "Basiliximab 20 mg vial",
  "Bedaquiline 100 mg tablet",
  "Beractant 25 mg/mL, 4 mL Depot Powder for Injection Vial",
  "Beractant 25 mg/mL, 8 mL Suspension for Injection Vial",
  "Betahistine 16 mg Tablet",
  "Betahistine 24 mg Tablet",
  "Betahistine 8 mg Tablet",
  "Betamethasone 0.1%, 5 g Cream Tube",
  "Betamethasone 0.1%, 5 g Ointment Tube",
  "Betaxolol 0.5%, 5 mL Eye Drops Bottle",
  "Bicalutamide 50 mg Tablet",
  "Biperiden 2 mg Tablet",
  "Biphasic Isophane Human Insulin 70/30 (Recombinant Dna) 100 IU/mL, 10 mL Suspension for Injection Vial",
  "Bisacodyl 10 mg Suppository",
  "Bisacodyl 5 mg Suppository",
  "Bisacodyl 5 mg Tablet",
  "Bleomycin 15 IU Powder for Injection Vial",
  "Brimonidine 0.15%, 5 mL Eye Drops Bottle",
  "Bromocriptine 2.5 mg tablet",
  "Budesonide 250 mcg/mL, 2 mL Respiratory Solution",
  "Budesonide Formoterol 160 mcg + 4.5 mcg, 120 doses Metered Dose Inhaler",
  "Budesonide Formoterol 160 mcg + 4.5 mcg, 60 doses Dry Powder Inhaler",
  "Budesonide Formoterol 80 mcg + 4.5 mcg, 60 doses Dry Powder Inhaler",
  "Bupivacaine 0.5%, 10 mL Solution for Injection Ampule",
  "Bupivacaine 0.5%, 10 mL Solution for Injection Vial",
  "Bupivacaine 0.5%, 5 mL Solution for Injection Ampule",
  "Bupivacaine Dextrose 0.5% + 8%, 4 mL Solution for Injection Vial",
  "Butamirate 50 mg Modified Release Tablet",
  "Butamirate 7.5 mg/5 mL, 120 mL Syrup Bottle",
  "Butorphanol 2 mg/mL, 1 mL Solution for Injection Ampule",
  "Calamine 8%, 60 mL Lotion Bottle",
  "Calcipotriol Betamethasone 50 meg 500 mcg/g. 30g tube",
  "Calcium (equiv. to 500 mg elemental calcium) Chewable Tablet",
  "Calcium (equiv. to 500 mg elemental calcium) Tablet",
  "Calcium . Cholecalciferol (Vitamin D3) Equiv. to 600 mg elemental calcium 400 IU Film Coated Tablet",
  "Calcium Carbonate 500 mg Chewable Tablet",
  "Calcium Carbonate 500 Tablet",
  "Calcium Cholecalciferol (Vitamin D3) Equiv. to 500 mg elemental calcium 400 IU Film Coated Tablet",
  "Calcium Folinate (Leucovorin Calcium) 10 mg/mL 5 mL Solution for Injection Ampule",
  "Calcium Folinate (Leucovorin Calcium) 10 mg/mL 5 mL Solution for Injection Vial",
  "Calcium Gluconate 10% 10 mL Solution for Injection Ampule",
  "Calcium Gluconate 10% 10 mL Solution for Injection Vial",
  "Calcium Gluconate 10% 20 mL Solution for Injection Bottle",
  "Capecitabine 500 mg Tablet",
  "Captopril 25 mg Tablet",
  "Carbamazepine 200 mg Tablet",
  "Carbetocin 100 mcg/mL 1 mL Solution for injection Ampule",
  "Carbetocin 100 meg/ml. 1 mL Solution for injection Vial",
  "Carbidopa . Levodopa 250 mg- 25 mg Tablet",
  "Carbidopa Levodopa 100 mg 25 mg Tablet",
  "Carboplatin 10 mg/mL, 15 mL Solution for Injection Vial",
  "Carboplatin 10 mg/mL, 45 mL Solution for Injection Vial",
  "Carboplatin 150 mg Powder for Injection Vial",
  "Carboplatin 450 mg Powder for Injection Vial",
  "Carboprost 125 mcg/0.5 mL, 0.5 mL Solution for Injection Ampule",
  "Carboprost 125 mcg/0.5 mL, 0.5 mL Solution for Injection Vial",
  "Carboprost 250 mcg/mL, 1 mL Solution for Injection Ampule",
  "Carboprost 250 mcg/mL, 1 mL Solution for Injection Vial",
  "Carvedilol 25 mg Tablet",
  "Carvedilol 6.25 mg Tablet",
  "Cefalexin 100 mg/mL, 10 mL Oral Drops Bottle",
  "Cefalexin 250 mg/5 mL, 60 mL Oral Suspension Bottle",
  "Cefalexin 250 mg/5 mL, 60 mL Syrup Bottle",
  "Cefalexin 500 mg Capsule",
  "Cefazolin 1 g Powder for Injection Vial",
  "Cefepime 1 g Powder for Injection Vial",
  "Cefepime 2 g Powder for Injection Vial",
  "Cefepime 500 mg Powder for Injection Vial",
  "Cefixime 100 mg/5 mL, 60 mL Oral Suspension Bottle",
  "Cefixime 20 mg/mL, 10 mL Oral Drops Bottle",
  "Cefixime 200 mg Capsule",
  "Cefixime 400 mg Capsule",
  "Cefotaxime 250 mg Powder for Injection Vial + 2 mL Diluent",
  "Cefotaxime 500 mg Powder for Injection Vial + 2 mL Diluent",
  "Cefoxitin 1 g Powder for Injection Vial",
  "Ceftaxidime (Ceftazidime) 1 g Powder for Injection Vial",
  "Ceftaxidime (Ceftazidime) 500 mg Powder for Injection Vial",
  "Ceftriaxone 1 g Powder for Injection Vial + 10 mL Diluent",
  "Cefuroxime 1.5 g Powder for Injection Vial",
  "Cefuroxime 125 mg/5 mL, 70 mL Oral Suspension Bottle",
  "Cefuroxime 250 mg/5 mL, 120 mL Bottle",
  "Cefuroxime 250 mg/5 mL, 50 mL Oral Suspension Bottle",
  "Cefuroxime 500 mg Tablet",
  "Cefuroxime 750 mcg Powder for Injection Vial",
  "Celecoxib 100 mg Capsule",
  "Celecoxib 200 mg Capsule",
  "Celecoxib 400 mg Capsule",
  "Cetirizine 1 mg/mL, 30 mL Oral Solution Bottle",
  "Cetirizine 1 mg/mL, 60 mL Oral Solution Bottle",
  "Cetirizine 10 mg Tablet",
  "Cetirizine 10 mg/mL, 10 mL Oral Drops Bottle",
  "Cetirizine 2.5 mg/mL, 10 mL Oral Drops Bottle",
  "Cetirizine 5 mg/5 mL, 30 mL Syrup Bottle",
  "Chloramphenicol 1 g Powder for Injection Vial",
  "Chlorhexidine 0.12%, 120 mL Oral Solution Bottle",
  "Chlorhexidine 0.12%, 380 mL Oral Solution Bottle",
  "Chlorphenamine (Chlopheniramine) 10 mg/mL, 1 mL Solution for Injection Ampule",
  "Chlorphenamine (Chlopheniramine) 4 mg Tablet",
  "Chlorpromazine 100 mg Tablet",
  "Chlorpromazine 200 mg Tablet",
  "Ciclosporin 100 mg/mL, 50 mL oral solution",
  "Cilostazol 100 mg Tablet",
  "Cilostazol 50 mg Tablet",
  "Cinnarizine 25 mg Tablet",
  "Ciprofloxacin 2 mg/mL, 100 mL Solution for Injection Vial",
  "Ciprofloxacin 2 mg/mL, 200 mL Solution for Injection Vial",
  "Ciprofloxacin 500 mg Tablet",
  "Cisplatin 1 mg/mL, 10 mL Solution for Injection Vial",
  "Cisplatin 1 mg/mL, 50 mL Solution for Injection Vial",
  "Clarithromycin 125 mg/5 mL, 50 mL Oral Suspension Bottle",
  "Clarithromycin 250 mg/5 mL, 50 mL Oral Suspension Bottle",
  "Clarithromycin 500 mg Tablet",
  "Clindamycin 150 mg Capsule",
  "Clindamycin 150 mg/mL, 2 mL Solution for Injection Ampule",
  "Clindamycin 150 mg/mL, 4 mL Solution for Injection Ampule",
  "Clindamycin 300 mg Capsule",
  "Clindamycin 75 mg/5 mL, 60 mL Oral Suspension Bottle",
  "Clobetasol 0.05%, 5 g Cream Tube",
  "Clobetasol 0.05%, 5 g Ointment Tube",
  "Clonazepam 2 mg Tablet",
  "Clonidine 150 mcg Tablet",
  "Clonidine 150 mcg/mL, 1 mL Solution for Injection Ampule",
  "Clonidine 75 mcg Tablet",
  "Clopidogrel 75 mg Tablet",
  "Cloxacillin 250 mg/5 mL, 60 mL Oral Solution Bottle",
  "Cloxacillin 500 mg Capsule",
  "Clozapine 100 mg Tablet",
  "Clozapine 25 mg Tablet",
  "Co-Amoxiclav (Amoxicillin + Clavulanic Acid) 200 mg + 28.5 mg/5 mL, 70 mL Oral Suspension Bottle",
  "Co-Amoxiclav (Amoxicillin + Clavulanic Acid) 400 mg + 57 mg/5 mL, 70 mL Oral Suspension Bottle",
  "Co-Amoxiclav (Amoxicillin + Clavulanic Acid) 500 mg + 125 mg Tablet",
  "Co-Amoxiclav (Amoxicillin + Clavulanic Acid) 600 mg + 42.9 mg/5 mL, 50 mL Oral Suspension Bottle",
  "Co-Amoxiclav (Amoxicillin + Clavulanic Acid) 875 mg + 125 mg Tablet",
  "Colchicine 500 mcg Tablet",
  "Colistin 2,000,000 IU Powder for Injection Vial",
  "Conjugated Estrogen 625 mcg Tablet",
  "Cotrimoxazole (Sulfamethoxazole + Trimethoprim) 400 mg + 80 mg Tablet",
  "Cotrimoxazole (Sulfamethoxazole + Trimethoprim) 800 mg + 160 mg Tablet",
  "Cotrimoxazole (Sulfamethoxazole) 400 mg + 80 mg/5 mL, 60 mL Oral Suspension Bottle",
  "Cyclophosphamide 1 g Powder for Injection Vial",
  "Cyclophosphamide 500 mg Powder for Injection Vial",
  "Cytarabine 100 mg/mL, 1 mL Solution for Injection Vial",
  "Cytarabine 100 mg/mL, 5 mL Solution for Injection Vial",
  "Dacarbazine 200 mg Powder for Injection Vial",
  "Daclatasvir 60 mg tablet",
  "Dactinomycin 500 mcg Powder for Injection Vial",
  "Deferasirox 125 mg dispersible tablet",
  "Deferasirox 250 mg dispersible Tablet",
  "Deferiprone 500 mg Tablet",
  "Deferoxamine 500 mg vial",
  "Desmopressin 100 mcg tablet",
  "Dexamethasone ! 5 mg/mL, 1 mL Solution for Injection Ampule",
  "Dexamethasone + Tobramycin 0.1% + 0.3%, 5 mL Eye Drops Bottle",
  "Dexamethasone 4 mg Tablet",
  "Dexamethasone 4 mg/mL, 1 mL Solution for Injection Vial",
  "Dexamethasone 4 mg/mL, 2 mL Solution for Injection Ampule",
  "Dexamethasone 4 mg/mL, 2 mL Solution for Injection Vial",
  "Dexamethasone 500 mcg Tablet",
  "Dextran, High Molecular Weight (Dextran 70) + Dextrose 6% + 5%, 500 mL Solution for Injection Bottle",
  "Dextran, High Molecular Weight (Dextran 70) + Sodium Chloride 6% + 0.9%, 500 mL Solution for Injection Bottle",
  "Dextrose + Lactated Ringer's 5%, 1 L Solution for Injection Bottle",
  "Dextrose + Lactated Ringer's 5%, 500 mL Solution for Injection Bottle",
  "Dextrose + Sodium Chloride 5% + 0.3%, 1 L Solution for Injection Bottle",
  "Dextrose + Sodium Chloride 5% + 0.3%, 500 mL Solution for Injection Bottle",
  "Dextrose + Sodium Chloride 5% + 0.9%, 1 L Solution for Injection Bottle",
  "Dextrose + Sodium Chloride 5% + 0.9%, 500 mL Solution for Injection Bottle",
  "Dextrose In Water 10%, 1 L Solution for Injection Bottle",
  "Dextrose In Water 10%, 500 mL Solution for Injection Bottle",
  "Dextrose In Water 5%, 1 L Solution for Injection Bottle",
  "Dextrose In Water 5%, 250 mL Solution for Injection Bottle",
  "Dextrose In Water 5%, 500 mL Solution for Injection Bottle",
  "Diazepam 5 mg Tablet",
  "Diazepam 5 mg/mL, 2 mL Solution for Injection Ampule",
  "Dibasic Sodium Phosphate + Monobasic Sodium Phosphate 19 g + 7 g/118 mL, 133 mL Rectal Solution Bottle",
  "Diclofenac 25 mg/mL, 3 mL Solution for Injection Ampule",
  "Diclofenac 50 mg Tablet",
  "Dicycloverine (Dicyclomine) 10 mg Tablet",
  "Dicycloverine (Dicyclomine) 10 mg/5 mL, 60 mL Syrup Bottle",
  "Diethylcarbamazine 50 mg tablet",
  "Digoxin 250 mcg Tablet",
  "Digoxin 250 mcg/mL, 2 mL Solution for Injection Ampule",
  "Digoxin 50 mcg/mL, 60 mL Oral Elixir Bottle",
  "Diltiazem 60 mg Tablet",
  "Diphenhydramine 12.5 mg/5 mL, 60 mL Syrup Bottle",
  "Diphenhydramine 25 mg Capsule",
  "Diphenhydramine 50 mg Capsule",
  "Diphenhydramine 50 mg/mL, 1 mL Solution for Injection Ampule",
  "Divalproex Sodium (Sodium Valproate + Valproic Acid) 250 mg Extended Release Tablet",
  "Divalproex Sodium (Sodium Valproate + Valproic Acid) 250 mg Tablet",
  "Divalproex Sodium (Sodium Valproate + Valproic Acid) 500 mg (133 mg + 145 mg) Extended Release Tablet",
  "Divalproex Sodium (Sodium Valproate + Valproic Acid) 500 mg Tablet",
  "Dobutamine 50 mg/mL, 5 mL Solution for Injection Ampule",
  "Docetaxel 20 mg/0.5 mL, 0.5 mL Solution for Injection Vial",
  "Docetaxel 20 mg/mL, 1 mL Solution for Injection Vial",
  "Docetaxel 40 mg/mL, 2 mL Solution for Injection Vial",
  "Docetaxel 80 mg/4mL, 4mL Concentrate Solution for Infusion Vial",
  "Domperidone 1 mg/mL, 60 mL Suspension for Injection Bottle",
  "Domperidone 10 mg Tablet",
  "Donepezil 10 mg Tablet",
  "Donepezil 5 mg Tablet",
  "Dopamine 40 mg/mL, 5 mL Solution for Injection Ampule",
  "Dorzolamide 2%, 5 mL Eye Drops Bottle",
  "Doxorubicin 10 mg Powder for Injection Vial",
  "Doxorubicin 2 mg/mL, 25 mL Solution for Injection Vial",
  "Doxorubicin 2 mg/mL, 5 mL Solution for Injection Vial",
  "Doxorubicin 50 mg Powder for Injection Vial",
  "Doxycycline 100 mg Capsule",
  "Dydrogesterone 10 mg Tablet",
  "Efavirenz 600 mg tablet",
  "Enalapril 20 mg Tablet",
  "Enalapril 5 mg Tablet",
  "Enoxaparin 100 mg/mL, 0.4 mL Solution for Injection Pre-filled Syringe",
  "Enoxaparin 100 mg/mL, 0.6 mL Solution for Injection Pre-filled Syringe",
  "Eperisone 50 mg Tablet",
  "Epinephrine (Adrenaline) 1 mg/mL, 1 mL Solution for Injection Ampule",
  "Epinephrine + Lidocaine 20 mg + 10 mcg/mL, 1.8 mL Solution for Injection Carpule",
  "Epirubicin 10 mg Powder for Injection Vial",
  "Epirubicin 50 mg Powder for Injection Vial",
  "Epoetin Alfa (Recombinant Human Erythropoetin) 10,000 IU/mL Solution for Injection Pre-filled Syringe",
  "Epoetin Alfa (Recombinant Human Erythropoetin) 4000 IU/0.4 mL Solution for Injection Pre-filled Syringe",
  "Epoetin Alfa (Recombinant Human Erythropoetin) 4000 IU/mL, 1 mL Solution for Injection Vial",
  "Epoetin Beta (Recombinant Erythropoetin) 2000 IU/0.3 mL Solution for Injection Pre-filled Syringe",
  "Epoetin Beta (Recombinant Erythropoetin) 5000 IU/0.3 mL Solution for Injection Pre-filled Syringe",
  "Ertapenem 1 g Powder for Injection Vial",
  "Erythromycin 0.5%, 3.5 g Eye Ointment Tube",
  "Erythromycin 0.5%, 5 g Eye Ointment Tube",
  "Erythromycin 200 mg/5 mL, 60 mL Oral Suspension",
  "Erythromycin 500 mg Tablet",
  "Escitalopram 10 mg Tablet",
  "Esmolol 10 mg/mL, 10 mL Solution for Injection Vial",
  "Esmolol 100 mg/mL, 10 mL Solution for Injection Vial",
  "Ethambutol + Isoniazid + Pyrazinamide + Rifampicin 75 mg + 150 mg + 400 mg + 275 mg Tablet",
  "Ethambutol 400 mg Tablet",
  "Ethinylestradiol + Levonorgestrel 30 mcg + 150 mcg Tablet",
  "Ethyl Alcohol 70%, 1 Gallon Solution",
  "Ethyl Alcohol 70%, 500 mL Solution Bottle",
  "Etonogestrel 68 mg subdermal implant",
  "Etoposide 20 mg/mL, 5 mL Solution for Injection Ampule",
  "Etoposide 20 mg/mL, 5 mL Solution for Injection Vial",
  "Famotidine 20 mg Powder for Injection Vial",
  "Felodipine 10 mg Modified Release Tablet",
  "Felodipine 5 mg Modified Release Tablet",
  "Fenofibrate 160 mg Tablet",
  "Fenofibrate 200 mg Capsule",
  "Fentanyl 50 mcg/mL, 10 mL Solution for Injection Ampule",
  "Fentanyl 50 mcg/mL, 2 mL Solution for Injection Ampule",
  "Ferrous Salt (e quiv. to 15 mg elemental iron)/0.6 mL, 15 mL Oral Drops",
  "Ferrous Salt (equiv. to 30 mg elemental iron)/5 mL, 60 mL Syrup",
  "Ferrous Salt (equiv. to 60 mg elemental iron) Tablet",
  "Ferrous Salt + Folic Acid 60 mg elemental iron + 400 mcg Capsule",
  "Ferrous Salt + Folic Acid 60 mg elemental iron + 400 mcg Film Coated Tablet",
  "Ferrous Salt + Folic Acid 60 mg elemental iron + 400 mcg Tablet",
  "Filgrastim (G-CSF) 300 mcg/0.5 mL, 0.5 mL Solution for Injection Pre-filled Syringe",
  "Filgrastim (G-CSF) 300 mcg/1.2 mL, 1.2 mL Solution for Injection Vial",
  "Filgrastim (G-CSF) 300 mcg/mL, 1 mL Solution for Injection Vial",
  "Finasteride 5 mg Tablet",
  "Fluconazole 150 mg Capsule",
  "Fluconazole 2 mg/mL, 100 mL Solution for Injection Vial",
  "Fluconazole 200 mg Capsule",
  "Fluconazole 50 mg Capsule",
  "Flumazenil 100 mcg/mL, 5 mL Solution for Injection Ampule",
  "Fluocinolone Acetonide + Neomycin + Polymyxin B 0.025% + 3.5 mg + 10,000 units/mL, 5 mL Ear Drops Bottle",
  "Fluorouracil 50 mg/mL, 10 mL Solution for Injection Vial",
  "Fluoxetine 20 mg Capsule",
  "Flupentixol 20 mg/mL, 1 mL Solution for Injection Ampule",
  "Fluphenazine 25 mg/mL, 1mL ampul",
  "Fluticasone + Salmeterol 125 mcg + 25 mcg, 120 actuations Metered Dose Inhaler",
  "Fluticasone + Salmeterol 250 mcg + 25 mcg, 120 actuations Metered Dose Inhaler",
  "Fluticasone + Salmeterol 50 mcg + 25 mcg, 120 actuations Metered Dose Inhaler",
  "Fluticasone + Salmeterol 500 mcg + 50 mcg, 60 doses Dry Powder Inhaler",
  "Fluticasone 0.05%/dose, 120 doses Nasal Solution",
  "Fluticasone 50 mcg/dose, 120 doses Metered Dose Inhaler",
  "Fluticasone Formoterol 125 mcg + 5 mcg, 120 actuations Metered Dose Inhaler",
  "Fluticasone Salmeterol 250 mcg + 50 mcg, 60 doses Dry Powder Inhaler",
  "Folic Acid 5 mg Capsule",
  "Folic Acid 5 mg Tablet",
  "Fondaparinux 2.5 mg/0.5 mL Solution for Injection Pre-filled Syringe",
  "Formoterol 12 mcg dry powder",
  "Fosfomycin 3 g Oral Granules Sachet",
  "Furosemide 10 mg/mL, 2 mL Solution for Injection Ampule",
  "Furosemide 20 mg Tablet",
  "Furosemide 40 mg Tablet",
  "Fusidate Sodium/Fusidic Acid 2%, 15 g Ointment",
  "Fusidate Sodium/Fusidic Acid 2%,5g Cream",
  "Gabapentin 100 mg Capsule",
  "Gabapentin 300 mg Capsule",
  "Gadobutrol 1 mmol/mL, 5 ml Solution for Injection Pre-filled Syringe",
  "Gadoteric Acid 0.5 mmol/mL, 10 ml Solution for InjectionVial",
  "Gemcitabine 1 g Powder for Injection Vial",
  "Gemcitabine 200 mg Powder for Injection Vial",
  "Gentamicin 40 mg/mL, 2 mL Solution for Injection Ampule",
  "Gliclazide 30 mg Modified Release Tablet",
  "Gliclazide 60 mg Modified Release Tablet",
  "Gliclazide 80 mg Tablet",
  "Glucose (Dextrose) 50%, 50 mL Solution for Injection Vial",
  "Glyceryl Trinitrate (Nitroglycerine) 1 mg/mL, 10 mL Ampule",
  "Glycopyrronium + Indacaterol 110 mcg + 50 mcg Dry Powder Capsule for Inhalation",
  "Goserelin 10.8 mg pre-filled syringe",
  "Goserelin 3.6 mg pre-filled syringe",
  "Haloperidol 5 mg Tablet",
  "Haloperidol 5 mg/mL, 1 mL Solution for Injection Ampule",
  "Heparin (Unfractionated) 1000 1U/mL, 5 mL Solution for Injection Vial (Bovine Origin)",
  "Heparin (Unfractionated) 5000 IU/mL, 5 mL Solution for Injection Vial (Bovine Origin)",
  "Human Recombinant Tissue Type Plasminogen- Activator (Alteplase) 50 mg powder",
  "Hydralazine 20 mg/mL, 1 mL Solution for Injection Ampule",
  "Hydrochlorothiazide + Irbesartan 150 mg + 12.5 mg Tablet",
  "Hydrochlorothiazide + Telmisartan 12.5 mg + 40 mg Tablet",
  "Hydrochlorothiazide + Valsartan 12.5 mg + 80 mg Tablet",
  "Hydrochlorothiazide Losartan 50 mg + 12.5 mg Tablet",
  "Hydrocortisone 1%, 10 g Cream Tube",
  "Hydrocortisone 1%, 5 g Cream Tube",
  "Hydrocortisone 100 mg Powder for Injection Vial",
  "Hydrocortisone 125 mg/mL, 2 mL Vial",
  "Hydrocortisone 250 mg Powder for Injection Vial",
  "Hydrocortisone 50 mg/mL, 2 mL Vial",
  "Hydrogen Peroxide 3%, 120 mL Solution Bottle",
  "Hydroxychloroquine 200 mg Tablet",
  "Hydroxyethyl Starch 6%, 500 mL Solution for Injection Bottle",
  "Hydroxyurea 500 mg Capsule",
  "Hyoscine 10 mg Tablet",
  "Hyoscine 20 mg/mL, 1 mL Solution for Injection Ampule",
  "Hypertonic Lactate 250 mL Solution for Injection Bag",
  "Hypromellose 0.3%, 10 mL Eye Drops Bottle",
  "Ibuprofen 100 mg/5 mL, 60 mL Oral Suspension",
  "Ibuprofen 200 mg Tablet",
  "Ibuprofen 200 mg/5 mL, 60 mL Oral Suspension",
  "Ibuprofen 400 mg Tablet",
  "Ifosfamide 1 g Powder for Injection Vial",
  "Ifosfamide 2 g Powder for Injection Vial",
  "Imatinib 100 mg Tablet",
  "Imatinib 400 mg Tablet",
  "Immunoglobulin Normal, Human (IGIV) 5 g Powder for Injection Bottle + 100 mL Diluent",
  "Immunoglobulin Normal, Human (IGIV) 50 mg/mL, 100 mL Vial",
  "Immunoglobulin Normal, Human (IGIV) 50 mg/mL, 50 mL Vial",
  "Immunoglobulin, Antithymocyte 25 mg/5 mL vial",
  "Immunoglobulin, Hepatitis B (Human), 0.5 mL Vial",
  "Immunoglobulin, Tetanus (Human) 250 1U/mL, 1 mL Solution for Injection Pre-filled Syringe",
  "Immunoglobulin, Tetanus (Human) 250 1U/mL, 1 mL Solution for Injection Vial",
  "Intraocular Irrigating Solution (Balanced Salt Solution), 500 mL Solution Bottle",
  "Ipratropium + Fenoterol 20 mcg + 50 mcg, 10 mL doses",
  "Ipratropium + Salbutamol 20 mcg + 100 mcg, 200 doses Metered Dose Inhaler",
  "Ipratropium + Salbutamol 500 mcg + 2.5 mg, 2.5 mL Respiratory Solution",
  "Irbesartan 150 mg Tablet",
  "Irbesartan 300 mg Tablet",
  "Irinotecan 20 mg/mL, 2 mL Solution for Injection Vial",
  "Irinotecan 20 mg/mL, 5 mL Solution for Injection Vial",
  "Iron Sucrose 20 mg/mL, 5 mL Solution for Injection Ampule",
  "Isoflurane, 100 mL Volatile Liquid for Inhalation Bottle",
  "Isoniazid + Rifampicin 75 mg + 150 mg Tablet",
  "Isoniazid 200 mg/5 mL, 120 mL Syrup",
  "Isoniazid 300 mg tablet",
  "Isophane Insulin Human (Recombinant DNA) 100 IU/mL, 10 mL Suspension for Injection Vial",
  "Isosorbide Dinitrate 1 mg/mL, 10 mL Solution for Injection Ampule",
  "Isosorbide Dinitrate 10 mg Tablet",
  "Isosorbide Dinitrate 5 mg Sublingual Tablet",
  "Isosorbide-5-Mononitrate 30 mg Modified Release Capsule",
  "Isosorbide-5-Mononitrate 30 mg Modified Release Tablet",
  "Isosorbide-5-Mononitrate 60 mg Modified Release Capsule",
  "Isotonic electrolyte solution for IV infusion 1 L",
  "Isoxsuprine 10 mg Tablet",
  "Isoxsuprine 5 mg/mL, 2 mL Solution for Injection Ampule",
  "Itraconazole 100 mg Capsule",
  "Ketamine 50 mg/mL, 10 mL Solution for Injection Vial",
  "Ketoconazole 2% (20 mg/g), 15 g Cream Tube",
  "Ketoconazole 2% (20 mg/g), 3.5 g Cream Tube",
  "Ketorolac 30 mg/mL, 1 mL Solution for Injection Ampule",
  "Lactated Ringer's, 1 L Solution for Injection Bottle",
  "Lactated Ringer's, 500 mL Solution for Injection Bottle",
  "Lactulose 3.3 g/5 mL (3.35 g/5 mL), 120 mL Syrup Bottle",
  "Lagundi [Vitex Negundo L. (Fam. Verbenaceae)] 300 mg Tablet",
  "Lagundi [Vitex Negundo L. (Fam. Verbenaceae)] 300 mg/5 mL, 120 mL Syrup Bottle",
  "Lagundi [Vitex Negundo L. (Fam. Verbenaceae)] 300 mg/5 mL, 60 mL Syrup Bottle",
  "Lagundi [Vitex Negundo L. (Fam. Verbenaceae)] 600 mg Tablet",
  "Lamotrigine 100 mg Tablet",
  "Lamotrigine 50 mg Tablet",
  "Lansoprazole 30 mg Capsule",
  "Latanoprost 50 mcg/mL, 2.5 mL Eye Drops Bottle",
  "Letrozole 2.5 mg Film Coated Tablet",
  "Letrozole 2.5 mg Tablet",
  "Leucovorin Calcium (Calcium Folinate) 10 mg/mL, 5 mL Solution for Injection Vial",
  "Leuproreline 11.25 mg Depot Powder for Injection Vial + Diluent",
  "Leuproreline 3.75 mg Powder for Injection Vial + mL Diluent",
  "Levetiracetam 1 g Film Coated Tablet",
  "Levetiracetam 100 mg/mL, 300 mL Oral Solution Bottle",
  "Levetiracetam 100 mg/mL, 5 mL Solution for Injection Vial",
  "Levetiracetam 250 mg Film Coated Tablet",
  "Levetiracetam 500 mg Film Coated Tablet",
  "Levobupivacaine 5 mg/mL, 10 mL Solution for Injection Ampule",
  "Levofloxacin 5 mg/mL (0.5 % w/v), 5 mL Eye Drops Bottle",
  "Levofloxacin 5 mg/mL, 100 mL Solution for Injection Vial",
  "Levofloxacin 5 mg/mL, 150 mL Solution for Injection Vial",
  "Levofloxacin 500 mg Tablet",
  "Levofloxacin 750 mg Tablet",
  "Levothyroxine 100 mcg Tablet",
  "Levothyroxine 150 mcg Tablet",
  "Levothyroxine 50 mcg Tablet",
  "Lidocaine 10%, 50 mL Spray Bottle",
  "Lidocaine 2%, 1.8 mL carpule (with epinephrine)",
  "Lidocaine 2%, 20 mL Solution for Injection Ampule",
  "Lidocaine 2%, 5 mL Solution for Injection Ampule",
  "Lidocaine 2%, 5 mL Solution for Injection Vial",
  "Lidocaine 2%, 50 mL Solution for Injection Vial",
  "Linezolid 2 mg/mL, 300 mL Solution for Injection Bag",
  "Linezolid 600 mg Film Coated Tablet",
  "Lipids 20%, 100 mL Emulsion for Injection Bottle",
  "Lipids 20%, 250 mL Emulsion for Injection Bottle",
  "Lithium Carbonate 450 mg MR tablet",
  "lodixanol 652 mg/mL (equiv. to 320 mg Iodine), 50 mL Solution for Injection Vial",
  "lohexol 300 mg iodine/mL, 50 mL Solution for Injection Vial",
  "lohexol 350 mg iodine/mL, 100 mL Solution for Injection Vial",
  "lohexol 350 mg iodine/mL, 50 mL Solution for Injection Vial",
  "lopamidol 612 mg/mL (equiv. to 300 mg Iodine), 100 mL Solution for Injection Vial",
  "lopamidol 612 mg/mL (equiv. to 300 mg Iodine), 50 mL Solution for Injection Vial",
  "lopamidol 755 mg/mL (equiv. to 370 mg Iodine), 100 mL Solution for Injection Vial",
  "lopamidol 755 mg/mL (equiv. to 370 mg Iodine), 50 mL Solution for Injection Vial",
  "Loperamide 2 mg Capsule",
  "Lopinavir + Ritonavir 200 mg + 50 mg Tablet",
  "lopromide 300 mg/mL (equiv. to 623 mg Iodine), 50 mL Solution for Injection Vial",
  "lopromide 370 mg/mL (equiv. to 769 mg Iodine), 100 mL Solution for Injection Vial",
  "lopromide 370 mg/mL (equiv. to 769 mg Iodine), 50 mL Solution for Injection Vial",
  "Loratadine 10 mg Tablet",
  "Losartan 100 mg Tablet",
  "Losartan 50 mg Tablet",
  "loversol 636 mg/mL (equiv. to 300 mg/mL Iodine), 50 mL Solution for Injection Vial",
  "Lynesterol 500 mcg tablet cycle",
  "Magnesium Sulfate 250 mg/mL, 10 mL Solution for Injection Ampule",
  "Magnesium Sulfate 250 mg/mL, 20 mL Solution for Injection Vial",
  "Magnesium Sulfate 500 mg/mL, 2 mL Solution for Injection Ampule",
  "Mannitol 20%, 500 mL Solution for Injection Bottle",
  "Mebendazole 100 mg/5 mL, 60 mL Oral Suspension Bottle",
  "Mebendazole 500 mg Tablet",
  "Mecobalamin 500 mcg Tablet",
  "Mecobalamin 500 mcg/mL, 1 mL Solution for Injection Ampule",
  "Medicine 1",
  "Medicine 2",
  "Medicine 3",
  "Medicine 4",
  "Medroxyprogesterone 10 mg Tablet",
  "Medroxyprogesterone 150 mg/mL, 1 mL Suspension for Injection Vial",
  "Mefenamic Acid 250 mg Capsule",
  "Mefenamic Acid 500 mg Capsule",
  "Mefenamic Acid 500 mg Tablet",
  "Memantine 10 mg Film Coated Tablet",
  "Mercaptopurine 50 mg Tablet",
  "Meropenem 1 g Powder for Injection Vial",
  "Meropenem 500 mg Powder for Injection Vial",
  "Mesalazine 500 mg Enteric Coated Tablet",
  "Mesna (Sodium-2- Mercaptoethanesulphonate) 100 mg/mL, 4 mL Solution for Injection Ampule",
  "Metformin 500 mg Film Coated Tablet",
  "Metformin 850 mg Tablet",
  "Methimazole (Thiamazole) 5 mg Tablet",
  "Methotrexate 100 mg/mL, 10 mL Solution for Injection Vial",
  "Methotrexate 2.5 mg tablet (as base or sodium salt)",
  "Methotrexate 25 mg/mL, 2 mL Solution for Injection Vial",
  "Methyldopa 250 mg Tablet",
  "Methylergometrine (Methylergonovine) 200 mcg/mL, 1 mL Solution for Injection Ampule",
  "Methylprednisolone 1 g Powder for Injection Vial + 16 mL Diluent",
  "Methylprednisolone 125 mg Powder for Injection Vial + 2 mL Diluent",
  "Methylprednisolone 16 mg Tablet",
  "Methylprednisolone 4 mg Tablet",
  "Methylprednisolone 40 mg Powder for Injection Vial",
  "Methylprednisolone 500 mg Powder for Injection Vial + Diluent",
  "Metoclopramide 10 mg Tablet",
  "Metoclopramide 5 mg/5 mL, 60 mL Syrup Bottle",
  "Metoclopramide 5 mg/mL, 2 mL Solution for Injection Ampule",
  "Metoprolol 100 mg Tablet",
  "Metoprolol 50 mg Tablet",
  "Metronidazole 125 mg/5 mL, 60 mL Oral Suspension Bottle",
  "Metronidazole 5 mg/mL, 100 mL Solution for Injection Vial",
  "Metronidazole 500 mg Tablet",
  "Midazolam 1 mg/mL, 5 mL Solution for Injection Vial",
  "Midazolam 1 mg/mL, 5 mL Solution for Injection Ampule",
  "Midazolam 5 mg/mL, 1 mL Solution for Injection Ampule",
  "Midazolam 5 mg/mL, 3 mL Solution for Injection Ampule",
  "Modified Fluid Gelatin (Polymerisate Of Degraded Succinylated Gelatin) 4%, 500 mL Solution for Injection Bottle",
  "Montelukast 10 mg Tablet",
  "Montelukast 4 mg Chewable Tablet",
  "Montelukast 4 mg Oral Granules Sachet",
  "Montelukast 5 mg Chewable Tablet",
  "Morphine 10 mg Modified Release Tablet",
  "Morphine 10 mg/mL, 1 mL Solution for Injection Ampule",
  "Morphine 30 mg MR tablet",
  "Morphine 60 mg MR tablet",
  "Moxifloxacin 0.5% (5 mg/mL), 5 mL Eye Drops Bottle",
  "Moxifloxacin 400 mg Film Coated Tablet",
  "Multivitamins  Capsule",
  "Multivitamins  Tablet",
  "Multivitamins per 1 mL, 15 mL Oral Drops Bottle",
  "Multivitamins per 5 mL, 120 mL Syrup Bottle",
  "Multivitamins per 5 mL, 60 mL Syrup Bottle",
  "Mupirocin 2%, 15 g Cream Tube",
  "Mupirocin 2%, 15 g Ointment Tube",
  "Mupirocin 2%, 5 g Ointment Tube",
  "Mycophenolate Mofetil 500 mg Tablet",
  "Mycophenolic Acid 360 mg tablet",
  "Nalbuphine 10 mg/mL, 1 mL Solution for Injection Ampule",
  "Naloxone 400 mcg/mL, 1 mL Solution for Injection Ampule",
  "Naproxen 550 mg (equiv. to 500 mg Naproxen) Tablet",
  "Neostigmine 500 mcg/mL, 1 mL Solution for Injection Ampule",
  "Neostigmine 500 mcg/mL, 10 mL Solution for Injection Vial",
  "Nicardipine 1 mg/mL, 10 mL Solution for Injection Ampule",
  "Nicardipine 1 mg/mL, 2 mL Solution for Injection Ampule",
  "Nifedipine 10 mg Capsule",
  "Nifedipine 30 mg Modified Release Tablet",
  "Nimodipine 30 mg film-coated tablet",
  "Nitroglycerin (Glyceryl Trinitrate) 1 mg/mL, 10 mL Solution for Injection Ampule",
  "Norepinephrine 1 mg/mL, 10 mL Solution for Injection Ampule",
  "Norepinephrine 1 mg/mL, 2 mL Solution for Injection Ampule",
  "Norepinephrine 1 mg/mL, 4 mL Solution for Injection Ampule",
  "Norepinephrine 2 mg/mL, 4 mL Solution for Injection Ampule",
  "Nystatin 100,000 units/mL, 30 mL Oral Suspension Bottle",
  "Octreotide 100 mcg/mL, 1 mL Solution for Injection Ampule",
  "Ofloxacin 0.3%, 5 mL Ear Drops Bottle",
  "Ofloxacin 0.3%, 5 mL Eye Drops Bottle",
  "Ofloxacin 200 mg Tablet",
  "Olanzapine 10 mg Orodispersible Tablet",
  "Olanzapine 10 mg Tablet",
  "Omeprazole 20 mg Capsule",
  "Omeprazole 40 mg Capsule",
  "Omeprazole 40 mg Powder for Injection Vial + 10 mL solvent",
  "Ondansetron 2 mg/mL, 2 mL Solution for Injection Ampule",
  "Ondansetron 2 mg/mL, 4 mL Solution for Injection Ampule",
  "Ondansetron 8 mg Tablet",
  "Oral Rehydration Salts (75 - Replacement) 20.5 g Oral Powder Sachet",
  "Oxacillin 500 mg Powder for Injection Vial",
  "Oxaliplatin 5 mg/mL, 10 mL Solution for Injection Vial",
  "Oxaliplatin 5 mg/mL, 20 mL Solution for Injection Vial",
  "Oxaliplatin 50 mg Powder for Injection Vial",
  "Oxcarbazepine 300 mg Tablet",
  "Oxycodone + Naloxone 10 mg + 5 mg tablet",
  "Oxycodone + Naloxone 20 mg + 10 mg tablet",
  "Oxycodone + Naloxone 40 mg + 20 mg tablet",
  "Oxycodone + Naloxone 5 mg + 2.5 mg tablet",
  "Oxycodone 10 mg Extended Release Tablet",
  "Oxycodone 10 mg/mL, 1 mL Solution for Injection Ampule",
  "Oxytocin 10 IU/mL, 1 mL Solution for Injection Ampule",
  "Paclitaxel 6 mg/mL, 16.7 mL Solution for Injection Vial",
  "Paclitaxel 6 mg/mL, 17 mL Solution for Injection Vial",
  "Paclitaxel 6 mg/mL, 25 mL Solution for Injection Vial",
  "Paclitaxel 6 mg/mL, 43.4 mL Solution for Injection Vial",
  "Paclitaxel 6 mg/mL, 5 mL Solution for Injection Vial",
  "Paliperidone 100 mg/mL, 1 mL Prolonged Release Suspension for Injection Pre-filled Syringe",
  "Paliperidone Palmitate 150 mg/1.5 mL prolonged release suspension for injection",
  "Pantoprazole 20 mg Enteric Coated Tablet",
  "Pantoprazole 40 mg Tablet",
  "Paracetamol 10 mg/mL, 100 mL Solution for Injection Vial",
  "Paracetamol 10 mg/mL, 50 mL Solution for Injection Vial",
  "Paracetamol 100 mg/mL, 15 mL Oral Drops Bottle",
  "Paracetamol 120 mg/5 mL (125 mg/5 mL), 60 mL Oral Suspension Bottle",
  "Paracetamol 120 mg/5 mL (125 mg/5 mL), 60 mL Syrup Bottle",
  "Paracetamol 125 mg Suppository",
  "Paracetamol 150 mg/mL, 2 mL Solution for Injection Ampule",
  "Paracetamol 250 mg Suppository",
  "Paracetamol 250 mg/5 mL, 60 mL Syrup Bottle",
  "Paracetamol 250 mg/5 mL, 60 mL Oral Suspension Bottle,",
  "Paracetamol 500 mg Tablet",
  "Penicillin G Benzathine (Benzathine Benzylpenicillin) 1,200,000 units Modified Release Powder for Injection Vial",
  "Penicillin G Crystalline (Benyzylpenicillin) 1,000,000 units Powder for Injection Vial",
  "Penicillin G Crystalline (Benyzylpenicillin) 5,000,000 units Powder for Injection Vial",
  "Peritoneal Dialysis 1.5%, 2 L Solution for Injection Bag",
  "Peritoneal Dialysis 2.3%, 2 L Solution for Injection Bag",
  "Peritoneal Dialysis 4.25%, 2 L Solution for Injection Bag",
  "Permethrin 5%, 60 mL Lotion Bottle",
  "Pethidine (Meperidine) 50 mg/mL, 2 mL Solution for Injection Ampule",
  "Phenobarbital 30 mg Tablet",
  "Phenobarbital 60 mg Tablet",
  "Phenylephrine + Tropicamide 5 mg + 5 mg/mL, 10 mL Eye Drops Bottle",
  "Phenytoin 100 mg Capsule",
  "Phenytoin 125 mg/5 mL, 120 mL Oral Suspension Bottle",
  "Phenytoin 50 mg/mL, 2 mL Solution for Injection Ampule",
  "Phytomenadione (Phytonadione, Vitamin K1) 10 mg/mL, 1 mL Solution for Injection Ampule",
  "Piperacillin + Tazobactam 2 g + 250 mg Powder for Injection Vial",
  "Piperacillin + Tazobactam 4 g + 500 mg Powder for Injection Vial",
  "Polymyxin B 500,000 Units Powder for Injection Vial",
  "Potassium 10 mEq Tablet",
  "Potassium 2 mEq/mL, 20 mL Solution for Injection Vial",
  "Potassium 600 mg Tablet",
  "Potassium 750 mg  (equiv. to 10 mEq Potassium) Sustained Release Tablet",
  "Povidone Iodine 1%, 120 mL Oral Solution Bottle",
  "Povidone Iodine 1%, 60 mL Oral Solution Bottle",
  "Povidone Iodine 10%, 1 Gallon Solution Bottle",
  "Povidone Iodine 10%, 120 mL Solution Bottle",
  "Povidone Iodine 10%, 60 mL Solution Bottle",
  "Prednisolone 1%, 5 mL Eye Drops Bottle",
  "Prednisone 10 mg Tablet",
  "Prednisone 10 mg/5 mL, 60 mL Oral Suspension Bottle",
  "Prednisone 20 mg Tablet",
  "Prednisone 5 mg Tablet",
  "Propofol 10 mg/mL, 20 mL Emulsion for Injection Ampule",
  "Propofol 10 mg/mL, 50 mL Emulsion for Injection Vial",
  "Propranolol 10 mg Tablet",
  "Propranolol 40 mg Tablet",
  "Propylthiouracil 50 mg Tablet",
  "Protamine 10 mg/mL, 5 mL  Ampule",
  "Pyrazinamide 250 mg/5 mL, 120 mL Oral Suspension Bottle",
  "Pyridostigmine 60 mg Tablet",
  "Quetiapine 100 mg Tablet",
  "Quetiapine 200 mg Tablet",
  "Quetiapine 25 mg Tablet",
  "Quetiapine 300 mg Tablet",
  "Ranitidine 150 mg Tablet",
  "Ranitidine 25 mg/mL, 2 mL Solution for Injection Ampule",
  "Ranitidine 300 mg Tablet",
  "Regular, Insulin (Recombinant DNA Human) 100 IU/mL, 10 mL Solution for Injection Vial",
  "Remifentanil 1 mg Powder for Injection Vial",
  "Remifentanil 2 mg Powder for Injection Vial",
  "Rifampicin + Isoniazid 150 mg + 75 mg tablet",
  "Rifampicin 200 mg/5 mL, 120 mL Oral Suspension Bottle",
  "Rifaximin 200 mg Tablet",
  "Risperidone 1 mg Tablet",
  "Risperidone 2 mg Tablet",
  "Rituximab 10 mg/mL, 10 mL Solution for Injection Vial",
  "Rituximab 10 mg/mL, 50 mL Solution for Injection Vial",
  "Rocuronium 10 mg/mL, 5 mL Solution for Injection Vial",
  "Ropivacaine 10 mg/mL, 10 mL Solution for Injection Ampule,",
  "Rosuvastatin 10 mg Tablet",
  "Rosuvastatin 20 mg Tablet",
  "Sacubitril + Valsartan 100 mg (48.6 mg + 51.4 mg) Tablet",
  "Sacubitril + Valsartan 200 mg (97.2 mg + 102.8 mg) Tablet",
  "Sacubitril + Valsartan 50 mg (24.3 mg + 25.7 mg) Tablet",
  "Salbutamol 1 mg/mL (unit dose), 2.5 mL Respiratory Solution Ampule",
  "Salbutamol 100 mcg/dose, 200 actuations Breath Actuated Metered Dose Inhaler",
  "Salbutamol 100 mcg/dose, 200 actuations Metered Dose Inhaler",
  "Salbutamol 2 mg/5 mL, 60 mL Syrup Bottle",
  "Salbutamol 2 mg/mL, 2.5 mL Respiratory Solution",
  "Sambong [Blumea Balsamifera (L) Dc (Fam. Compositae)] 500 mg Tablet",
  "Sertraline 50 mg Tablet",
  "Serum Anti-Tetanus 1500 IU/mL, 1 mL Solution for Injection Ampule (Equine)",
  "Serum, Anti-Rabies 1500 IU/0.7 mL, 0.7 mL Solution for Injection Ampule (Equine)",
  "Serum, Anti-Rabies 200 IU/mL, 5 mL Solution for Injection Vial (Equine)",
  "Serum, Anti-Tetanus 1500 IU/0.7 mL, 0.7 mL Solution for Injection Vial (Equine)",
  "Sevelemer 800 mg film-coated tablet",
  "Sevoflurane, 250 mL Volatile Liquid for Inhalation Bottle",
  "Silver Sulfadiazine 1%, 15 g Cream Tube",
  "Silver Sulfadiazine 1%, 25 g Cream Tube",
  "Silver Sulfadiazine 1%, 500 g Cream Jar",
  "Simvastatin 20 mg Tablet",
  "Simvastatin 40 mg Tablet",
  "Sirolimus 0.5 mg tablet",
  "Sirolimus 1 mg tablet",
  "Sodium Bicarbonate 1 mEq/mL, 20 mL Solution for Injection Ampule",
  "Sodium Bicarbonate 1 mEq/mL, 50 mL Solution for Injection Ampule",
  "Sodium Bicarbonate 650 mg Tablet",
  "Sodium Chloride 0.9%, 1 L Solution Bottle (For Irrigation)",
  "Sodium Chloride 0.9%, 1 L Solution for Injection Bottle",
  "Sodium Chloride 0.9%, 10 mL Solution for Injection Ampule",
  "Sodium Chloride 0.9%, 100 mL Solution for Injection Bag",
  "Sodium Chloride 0.9%, 100 mL Solution for Injection Bottle",
  "Sodium Chloride 0.9%, 20 mL Solution for Injection Ampule",
  "Sodium Chloride 0.9%, 50 mL Solution for Injection Bottle",
  "Sodium Chloride 0.9%, 500 mL Solution for Injection Bottle",
  "Sodium Chloride 0.9%, 500 mL Solution for Injection Bag",
  "Sodium Chloride 2.5 mEq/mL, 20 mL Solution for Injection Vial",
  "Sodium Hyaluronate 0.1% (1mg/mL), 5 mL Eye Drops Bottle",
  "Sodium Valproate 200 mg/5 mL, 100 mL Syrup Bottle",
  "Sofosbuvir 400 mg tablet",
  "Somatostatin 250 mcg Powder for Injection Vial",
  "Somatostatin 3 mg Powder for Injection Ampule",
  "sosorbide-5-Mononitrate 60 mg Modified Release Tablet",
  "Spironolactone 100 mg Tablet",
  "Spironolactone 25 mg Tablet",
  "Spironolactone 50 mg Tablet",
  "Sterile Water For Injection, 1 L Bottle,",
  "Sterile Water For Injection, 10 mL Ampule",
  "Sterile Water For Injection, 100 mL Bottle",
  "Sterile Water For Injection, 20 mL Ampule",
  "Sterile Water For Injection, 50 mL Bottle",
  "Streptokinase 1,500,000 IU Powder or Injection Vial",
  "Streptomycin 1 g Powder for Injection Vial",
  "Sucralfate 1 g Tablet",
  "Sugammadex 100 mg/mL, 2 mL Solution for Injection Vial",
  "Suxamethonium (Succinylcholine) 20 mg/mL, 10 mL Solution for Injection Vial",
  "Tacrolimus 1 mg slow-release capsule",
  "Tacrolimus 5 mg slow-release capsule",
  "Tamoxifen 20 mg Tablet",
  "Tamsulosin 200 mcg Capsule",
  "Tamsulosin 200 mcg Orodispersible Tablet",
  "Tamsulosin 400 mcg Prolonged Release Film Coated Tablet",
  "Telmisartan 40 mg Tablet",
  "Telmisartan 80 mg Tablet",
  "Tenofovir Disoproxil 300 mg Tablet",
  "Terazosin 1 mg Tablet",
  "Terazosin 2 mg Tablet",
  "Terazosin 5 mg Tablet",
  "Terbutaline 500 mcg/mL, 1 mL Solution for Injection Ampule",
  "Thiopental Sodium 500 mg Powder for Injection Vial",
  "Timolol 0.5%, 5 mL Eye Drops Bottle",
  "Tinzaparin 10,000 anti-Xa IU/mL, 2 mL vial",
  "Tinzaparin 10,000 anti-XA IU/mL, 0.35 mL pre-filled syringe",
  "Tinzaparin 10,000 anti-XA IU/mL, 0.45 mL pre-filled syringe",
  "Tiotropium 18 mcg/dose with appropriate accompanying dispenser",
  "Tobramycin 0.3%, 3.5 g Eye Ointment Tube",
  "Tobramycin 0.3%, 5 mL Eye Drops Bottle",
  "Tolvaptan 15 mg Tablet",
  "Topiramate 25 mg Tablet",
  "Topiramate 50 mg Tablet",
  "Trace Elements (Contains Zn, Cu, Mn, Mg, Mb, Etc.), 10 mL Solution for Injection Ampule",
  "Tramadol 50 mg Capsule",
  "Tramadol 50 mg/mL, 1 mL Solution for Injection Ampule",
  "Tramadol 50 mg/mL, 2 mL Solution for Injection Ampule",
  "Tranexamic Acid 100 mg/mL, 5 mL Solution for Injection Ampule",
  "Tranexamic Acid 500 mg Capsule",
  "Tranexamic Acid 500 mg Tablet",
  "Trastuzumab 150 mg Powder for Injection Vial",
  "Trastuzumab 600 mg/5 mL (120 mg/mL) solution for injection, 5 mL vial",
  "Travoprost 0.004%, 2.5 mL Eye Drops Bottle",
  "Trimetazidine 35 mg Tablet",
  "Tropicamide 0.5%, 5 mL Eye Drops Bottle",
  "Tuberculin, Purified Protein Derivative 2 TU/0.1 mL, 1 mL vial",
  "Ursodeoxycholic Acid 250 mg Tablet",
  "Ursodeoxycholic Acid 250 mg Capsule",
  "Ursodeoxycholic Acid 500 mg Tablet",
  "Vaccine, BCG 500 mcg/mL vial + 1 mL diluent in ampule 20 doses",
  "Vaccine, BCG Vaccine 100 mcg/0.1 mL Powder for Injection Vial + 1 mL Diluent",
  "Vaccine, Diphtheria, Tetanus, Pertussis, Hepatitis B Recombinant and Haemophilus Influenza Type B (Hib) Combined 0.5 mL vial",
  "Vaccine, Hepatitis B (Recombinant) Vaccine 10 mcg/0.5 mL, 5 mL  Vial",
  "Vaccine, Hepatitis B (Recombinant) Vaccine 20 mcg/mL, 1 mL  Vial",
  "Vaccine, Human Papillomavirus Quadrivalent (types 6, 11, 16, 18) 0.5 mL",
  "Vaccine, Inactivated Poliomyelitis (Type 1, 2 and 3) 0.5 mL multidose vial",
  "Vaccine, Influenza Polyvalent 0.5 mL Suspension for Injection Pre-filled Syringe",
  "Vaccine, Influenza Polyvalent 15 mcg/0.5 mL, 5 mL multidose, glass vial",
  "Vaccine, Live Attenuated Measles, Mumps and Rubella (MMR) Multidose vial + 5 mL diluent (10 dose)",
  "Vaccine, Pneumococcal Conjugate Multi-dose vial",
  "Vaccine, Pneumococcal Polyvalent 25 mcg/0.5 mL, 0.5 mL single dose vial",
  "Vaccine, Rabies Chick Embryo Cell 2.5 IU Powder for Injection Vial + 1 mL Diluent (Purified, Inactivated)",
  "Vaccine, Tetanus Toxoid 40 IU (5 lf)/0.5 mL, 0.5 mL Suspension for Injection Ampule",
  "Vaccine, Vero Cell (Purified) 2.5 IU/0.5 mL vial + diluent",
  "Valaciclovir 500 mg Tablet",
  "Valganciclovir 450 mg tablet",
  "Valproic Acid 250 mg/5 mL, 120 mL Syrup Bottle",
  "Valsartan 160 mg Film Coated Tablet",
  "Valsartan 80 mg Film Coated Tablet",
  "Vancomycin 1 g Powder for Injection Vial",
  "Vancomycin 500 mg Powder for Injection Vial",
  "Verapamil 2.5mg/ml, 2mL Ampule",
  "Verapamil 80 mg Tablet",
  "Vinblastine 1 mg/mL, 10 mL Solution for Injection Vial",
  "Vinblastine 10 mg Powder for Injection Vial",
  "Vincristine 1 mg/mL, 1 mL Solution for Injection Vial",
  "Vincristine 1 mg/mL, 2 mL Solution for Injection Vial",
  "Vitamin B1 + Vitamin B12 + Vitamin B6 100 mg + 100 mg + 1 mg /mL, 3 mL Solution for Injection Ampule",
  "Vitamin B1 + Vitamin B12 + Vitamin B6 100 mg + 5 mg + 50 mcg Capsule",
  "Vitamin B1 + Vitamin B12 + Vitamin B6 100 mg + 5 mg + 50 mcg Tablet",
  "Voriconazole 200 mg Film Coated Tablet",
  "Voriconazole 200 mg Powder for Injection Vial",
  "Warfarin 2.5 mg Tablet",
  "Warfarin 5 mg Tablet",
  "Zinc (equiv. to 10 mg elemental/mL), 15 mL Oral Drops Bottle",
  "Zinc (equiv. to 20 mg elemental zinc/5 mL), 60 mL Syrup Bottle",
  "Zinc 70 mg/5 mL (equivalent to 10 mg elemental zinc), 60 mL Syrup Bottle",
  "Zolpidem 10 mg Tablet",
]